- hosts: www.example.com
  tasks:
    - name: User account state check
      user: name=userA state=present
      sudo: 'yes'
    - name: User authorized key state check
      authorized_key:
        user: userA
        key: "{{ lookup('file','userA.pub') }}"
        manage_dir: 'yes'
        state: present
      sudo: 'yes'
    - name: User account state check
      user: name=userB state=absent
      sudo: 'yes'
    - name: Group state check
      group: name=group1 state=present
      sudo: 'yes'
    - name: Group state check
      group: name=group2 state=present
      sudo: 'yes'
    - name: Group state check
      group: name=group3 state=present
      sudo: 'yes'
