- hosts: 192.168.122.137
  tasks:
    - name: User account state check
      user: name=demo state=present
      sudo: 'yes'
    - name: User authorized key state check
      authorized_key:
        user: demo
        key: "{{ lookup('file','/home/mark/.ssh/newton/id_rsa.pub') }}"
        manage_dir: 'yes'
        state: present
      sudo: 'yes'
