- hosts: 192.168.122.137
  tasks:
    - name: addUserAccount - User account state
      user: name=demo state=present
    - name: addUserAccount - User authorized key state check
      authorized_key:
        user: demo
        key: "{{ lookup('file','./conf-example/db/keys/user1.pub') }}"
        manage_dir: 'yes'
        state: present
